### PR TITLE
Enable CI service (circleci)

### PR DESCRIPTION
**Pull request by nomaddo**
This pullreq add two features:

- enable circleci (for auto-build hooked by `git push`)
   I added `.circleci/config.yml`: configuration file for auto-build in circleci.
- enable debian packaging (.deb) by `cpack`
  I modified `CMakeLists.txt` to enable it. Now, after execution of `cmake`, `cpack -G DEB` create debian package for rasberrypi.

Circleci enable us to build automatically by every `git push` to the project.
This provide a lot of benefit for us:

- auto-build 
  You can check that our commits can be built without compiling locally.
  And, this provide the result of the compilation (we call them artifacts).
  Everyone can download these artifacts by circleci website.
  (In my forked project, see https://circleci.com/gh/nomaddo/VC4C/7)
- build under Docker image (in this case, https://hub.docker.com/r/nomaddo/cross-rpi/)
  Docker is a standard container software (virtualize linux environment) to standardize develop environment.
  Generally, we suffer from the difference of development environment.
  By Docker, we can get the same development environment just by one command `docker pull`.
  I think my docker image (see upper url to hub.docker) is standard as a cross-compilation environment.

Circleci can be available for public repositories for free if we use it within 1800 min (enough for us!) in a month.
If you accept this pullreq, you need to a little bit work to enable circleci.
if you feel messy, please add me to the project colaborator. I will do everything.

I also make the same patch for `VC4CL`.

### CODE REVIEW

**Comment by nomaddo** [comment]
I think this kind of development environment is very important to keep development.
Artifacts, built by circleci, can be "master" files.
We test the same file, and find the same issue.
If we compile individually, the difference of development environment (os version, package version, mistaken build step, etc...) make us confused.

And, circleci config can be used for local build.
https://circleci.com/docs/2.0/local-jobs/

Now we can use the same development environment for cross-compilation, and new contributors can easily set up the environment.

**Comment by doe300** [comment]
First of all, many thanks for PR.

A few remarks:
- how can I download the build artifacts? Or can you provide me with a list of files packaged into the debian package?
- as fas as I can tell, the package created cannot yet be used (see #9). The fix for that problem lies outside of the scope of this PR, just something to note here.

**Comment by nomaddo** [comment]
Sorry for the delay.

**Comment by doe300** [comment]
I've pulled your PR and set up CircleCI (see [here](https://circleci.com/gh/doe300/VC4C/1)). Thanks again for the effort!

Some things are not correct:
- "Uploading artifacts" (I) errors with "No artifact files found at /root/project/build/{libVC4CC.so,libVC4CC.so.0.4,libVC4CC.so.1.2,VC4C}", same for the builds 9 and 10 of your PR
- The debian-package contains all the files (even the artifacts not found above), but no control-data

@nomaddo, do you have any idea what might be wrong?

**Comment by nomaddo** [comment]
Probably, my `circleci/config.yml` was wrong: it seem abbreviated notation didn't work.
Please see #10.

**Pull request merged**
